sudo: required
services:
  - docker

before_install:
  - docker build -t rocky1638/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rocky1638/docker-react yarn test --coverage # coverage option so the command acc exits

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-726141900843"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" # workaround?
